{% set version = "0.3.112" %}

package:
  name: libaio
  version: {{ version }}

source:
  url: https://releases.pagure.org/libaio/libaio-{{ version }}.tar.gz
  sha256: ab0462f2c9d546683e5147b1ce9c195fe95d07fac5bf362f6c01637955c3b492

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libaio', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f $PREFIX/lib/libaio${SHLIB_EXT}
    - test -f $PREFIX/include/libaio.h

about:
  home: https://pagure.io/libaio
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Provides the Linux-native API for async I/O'
  description: |
    The Linux-native asynchronous I/O facility ("async I/O", or "aio") has a
    richer API and capability set than the simple POSIX async I/O facility.
    This library, libaio, provides the Linux-native API for async I/O. The
    POSIX async I/O facility requires this library in order to provide
    kernel-accelerated async I/O capabilities, as do applications which require
    the Linux-native async I/O API.

extra:
  recipe-maintainers:
    - hmaarrfk
