travis:
  secure:
    BINSTAR_TOKEN: OAgpNAVeT8i9FRjp1Pf+xFVHViC0L0BHmcuRm1AhjhfdPOhH4Y2afNH3862KcykyKG+qEk330LsmofMpLun59ktHoOjEoygrFR2lTRzpWYcwBGf42vh+NNggjs5fWzOodpU0SZ2ohRriPpbMDv7PuaChvCNO4OcPmzw7vfRlwSyhEdTZxQqtY5aQy0XV9353Ce0jzAZugZDCaov3R69201mhngL+7nLUZYB18lNUFQwriwlMQkWOjSTomOlzEikOXtmJZ0MGypUjQlsZa7AaFNfMhbnuA9tvVKZEM7j2hntFTLpToWaVAdSc3L+18mK8Am3LRSf613cnHqbcZjk0/XwSZw1aWpjJ+Fzw6btb2z/TOYw+X7X7bTSUXj7Z3QTFBtThMHbe24q+pWvXauhhDtu+VCb7oNCYc6b4JPrVNNbew/sfiuBPEt2B+8FLb+h9N/egxhWqYypKkwuhxoFpadokNHQLcNlntv2XDJDVRhWwXA6ALxr9fdF/05lww+6Zo1enaYtsVVaZJvls+kKGGH2+Wh+15iu7jSGYwz3JBnIATv5s6yDces6XvnRp4wc4VmErRzjjBqh7+W2f2l/R37GeJsMarziYRSCvVHozdIyakcy7GJdOEULZUOvO0O3aOgMy74DBGdEnljOMTwvoDYl/z08aqveKyyL4op/dNz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
